version: "3"

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  blogex:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: blogex_dev
      PGPORT: 5432
      PGHOST: db
      GUARDIAN_SECRET: UaE9J9jqkLcBcV46r+WihLKwNea5HLz+X2eo3ij4CYBuelnEQo3eXi1QEIp4PzC2
    container_name: blogex
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/blogex
    depends_on:
      - db
volumes:
  pgdata:
